server:
  port: 8081

spring:
  datasource :
    url : jdbc:mysql://localhost:3306/library_system?createDatabaseIfNotExist=true
    username : root
    password : Sanuth2003
  jpa :
    hibernate :
      ddl-auto : update